[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # Must match your local version
  NODE_OPTIONS = "--max_old_space_size=4096"  # Double memory allocation